#dataset
train_dataset:
  data_path: '/home/li/mbes-cleaning/data-dotson-east-unfiltered/merged/all_data.npz'
  gt_path: '/home/li/mbes-cleaning/data-dotson-east-unfiltered/merged/all_data_draping_2.36mesh_gt_5.0m.npy'
  pings_subset: [0, 2000]
  pings_per_patch: 1
  transform:
    noise:
      type: 'add_noise_to_clean'
      min: 5
      max: 20
    rotate: 
      axis: 2
      max_angle: 180
val_dataset:
  data_path: '/home/li/mbes-cleaning/data-dotson-east-unfiltered/merged/all_data.npz'
  gt_path: '/home/li/mbes-cleaning/data-dotson-east-unfiltered/merged/all_data_draping_2.36mesh_gt_5.0m.npy'
  pings_subset: [1000, 1200]
  pings_per_patch: 1
  #transform: !!null
  transform:
    noise:
      type: 'add_noise_to_clean'
      min: 5
      max: 20

#dataloader
train_batch_size: 32
val_batch_size: 1
num_workers: 4

#model
dsm_sigma: 100
score_net_hidden_dim: 32
score_net_num_blocks: 2

#optimizer
lr: 0.001
weight_decay: 0.
max_grad_norm: !!float 'inf'
gamma: 0.9 # gamma for ExponentialLR

#training
seed: 2020
logging: True
log_root: './logs'
device: 'cuda'
max_epochs: 50
log_interval: 1
val_freq: 200
ld_step_size: .1
#tag: !!null
tag: '20240416-wandb-test'
num_train_points: 256
frame_knn: 10
num_clean_nbs: 5