#dataset
train_dataset:
  data_path: '/proj/berzelius-2023-154/users/x_lling/score-denoise/data/mbes-denoising/EM2040-0014-l04s01-20190618-175553.xyz.npz'
  gt_path: '/proj/berzelius-2023-154/users/x_lling/score-denoise/data/mbes-denoising/EM2040-0014-l04s01-20190618-175553_draping_gt_0.5m-tx-only-yaw-meridian-convergence-zoffset-+.361.npy'
  pings_subset: [200, 4000]
  pings_per_patch: 1
  transform: !!null
  # transform:
  #   noise:
  #     type: 'add_noise_to_clean'
  #     min: .5
  #     max: 2
  #   rotate: 
  #     axis: 2
  #     max_angle: 180
val_dataset:
  data_path: '/proj/berzelius-2023-154/users/x_lling/score-denoise/data/mbes-denoising/EM2040-0014-l04s01-20190618-175553.xyz.npz'
  gt_path: '/proj/berzelius-2023-154/users/x_lling/score-denoise/data/mbes-denoising/EM2040-0014-l04s01-20190618-175553_draping_gt_0.5m-tx-only-yaw-meridian-convergence-zoffset-+.361.npy'
  pings_subset: [2000, 2100]
  pings_per_patch: 1
  transform: !!null
  # transform:
  #   noise:
  #     type: 'add_noise_to_noisy'
  #     min: .5
  #     max: 5
  #   rotate: 
  #     axis: 2
  #     max_angle: 180

#dataloader
train_batch_size: 1024
val_batch_size: 1
num_workers: 4

#model
dsm_sigma: .1
score_net_hidden_dim: 32
score_net_num_blocks: 2

#optimizer
lr: 0.001
weight_decay: 0.
max_grad_norm: !!float 'inf'
lr_decay: 0.9 # gamma for ExponentialLR

#training
seed: 2020
logging: True
log_root: './logs'
device: 'cuda'
max_epochs: 50
log_interval: 1
val_freq: 200
ld_step_size: .1
#tag: !!null
tag: '20240423-gullmarsfjord-train=val-notransforms-knn=30-clean=1-no-centering'
num_train_points: 256
frame_knn: 30
num_clean_nbs: 1